Various small utility scripts for my =$PATH= under the =bin= directory. Some of
them may be fairly reusable as is for others, whereas other scripts may be very
specific to my setup 👉 [[https://github.com/vyp/dots][vyp/dots]].

* hlwm-polybar

A script to show focused, occupied, free and urgent herbstluftwm tags in polybar
using lemonbar formatting tags. It assumes it is being used only in a single
monitor setup for now.

* hlwm-tag

A small =herbstclient= wrapper script for use with
[[http://www.herbstluftwm.org][herbstluftwm]].

It can be used to either switch to, or move the focused client to, the next
occupied or free tag.

Usage:

#+BEGIN_SRC shell-script
$ hlwm-tag <action> <tag>
#+END_SRC

Where =<action>= is either =use=, =move= or =both=, and =<tag>= is either
=free= or =occupied=.

* latexmk-auxdir

Ideally, the following one-liner would just work:

#+BEGIN_SRC shell-script
$ latexmk -lualatex -ourdir=.aux && if .aux/*.pdf >/dev/null 2>&1; then ln -fs .aux/*.pdf .; fi
#+END_SRC

However, latexmk seems to recompile all .tex files regardless of whether they're
already up to date or not. So this wrapper script simply does the above, but is
restricted to just the one .tex source file. This is so it can be used with [[http://entrproject.org/][entr]]
and [[https://github.com/sharkdp/fd][fd]] like so:

#+BEGIN_SRC shell-script
$ { fd -e tex -d 1; fd -e png; fd -e jpg; } | entr latexmk-auxdir .aux /_
#+END_SRC
