#!/usr/bin/env bash

shopt -s extglob

interval='1200s'
shuffle=1

path="$HOME/pics/walls"
active_path="$path/active"

case "$1" in
  '?')
    echo $path
    ;;
  '_')
    echo daemon
    ;;
  '.')
    echo next
    ;;
  ',')
    echo prev
    ;;
  '-')
    echo remove
    ;;
  -+([a-z]))
    echo option
    ;;
  *)
    echo add
    ;;
esac
