#!/usr/bin/env zsh

. $BIN_CONFIG_HOME/wpd
[[ -p $fifo ]] || exit 1

if [[ "$1" == '-' ]]; then
  # '-' doesn't go through in zsh, but it does in bash..??
  # And so apparently ${@:2} needs to be used to cut off the hyphen, instead of
  # ${@:1} as you would expect.. :|
  echo '!' ${@:2} > $fifo
else
  echo "$@" > $fifo
fi
