#!/usr/bin/env zsh

local fifo='/tmp/wpd'

# NOTE: Has to be an absolute path.
local walls="$HOME/pics/walls"
# Array of filetypes to use as wallpapers. Use empty array to use any filetype.
# NOTE: Just checks filename suffix, doesn't /actually/ check the filetype.
local filetypes=(jpg png)
# Relative to ${walls}.
local active_dirname='active'

local interval=2
local shuffle=1
local cmd='setroot'
# Leave empty to pass no options.
local cmd_opts='-z'
